title: Ellen Duong
author: Ellen Duong

# Serving
port: 4000

excerpt_separator: <!-- more -->

exclude:
  - .idea/
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - INSTRUCTIONS.md
  - README.md
  - node_modules
  - package-lock.json
  - package.json
  - requirements.txt
  - venv/
  - webpack.config.js
  - _excludes/