title: Ellen Duong
author: Ellen Duong

# Serving
port: 4000

excerpt_separator: <!-- more -->
sass:
  style: compressed

exclude:
  - .idea/
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - package-lock.json
  - package.json
  - _excludes/